### Student 리스트
GET http://127.0.0.1:8080/students


### Student 조회
GET http://127.0.0.1:8080/students/OsS094wBn442ou3yVbq2


### Student 등록
POST http://127.0.0.1:8080/students
Content-Type: application/json

{
  "name": "박석영",
  "grade": 2,
  "age": 18
}


### Student 수정
PUT http://127.0.0.1:8080/students/OsS094wBn442ou3yVbq2
Content-Type: application/json

{
  "name": "박석영",
  "grade": 3,
  "age": 19
}

### Student 수정 ( update )
PUT http://127.0.0.1:8080/students/OsS094wBn442ou3yVbq2/update
Content-Type: application/json

{
  "name": "박석영",
  "grade": 3,
  "age": 15
}


### Student 삭제
DELETE http://127.0.0.1:8080/students/OcST94wBn442ou3y6rq4