# Student 리스트
GET http://127.0.0.1:8080/cacheable/students

###

# Student 조회
GET http://127.0.0.1:8080/cacheable/students/STUDENT:5r3SMS8cNND58C6R

###

# Student 등록
POST http://127.0.0.1:8080/cacheable/students
Content-Type: application/json

{
  "name": "박석영",
  "grade": 2,
  "age": 18
}

###

# Student 수정
PUT http://127.0.0.1:8080/cacheable/students/STUDENT:5r3SMS8cNND58C6R
Content-Type: application/json

{
  "name": "박석영",
  "grade": 2,
  "age": 19
}
###

# Student 삭제
DELETE http://127.0.0.1:8080/cacheable/students/STUDENT:jcoaO9Twekb6Sfc4

###